name: daily_messages
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.1
  http: ^1.2.1
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  internet_connection_checker: ^1.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
