name: new_bible_verse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  shared_preferences: ^2.4.0
  qr_flutter: ^4.1.0
  home_widget: ^0.6.0
  path_provider: ^2.0.11
  rename: ^3.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4


flutter_native_splash:
  color: "#333434"
  image: "assets/app/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/app/playstore.png"
  ios: true
  remove_alpha_ios: true
  android: launcher_icon
  adaptive_icon_background: "#EEE9DA"
  adaptive_icon_foreground: "assets/app/playstore.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

